spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
server:
  port: 8765


