server:
  port: 8765
spring:
  profiles:
    active: stage
  config:
    import: optional:configserver:http://localhost:8888
  jpa:
    defer-datasource-initialization: true
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
